# Generated by Django 3.2.7 on 2021-09-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='e_phase',
            options={'ordering': ('phase',), 'verbose_name': 'E_phase', 'verbose_name_plural': 'E_phases'},
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(blank=True, default='img', upload_to='media/products'),
        ),
    ]
