# Generated by Django 3.2.7 on 2021-09-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210930_2300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='e_phase',
            options={},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={},
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(blank=True, default='image', upload_to='media/products'),
        ),
    ]
