# Generated by Django 3.2.7 on 2021-09-30 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210930_2328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='e_phase',
            options={'ordering': ('phase',), 'verbose_name': 'E_phase', 'verbose_name_plural': 'E_phases'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ('name',), 'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
    ]
