# Generated by Django 3.2.7 on 2021-10-19 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_projects_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='E_phase',
        ),
    ]
