# Generated by Django 3.2.7 on 2021-10-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_delete_e_phase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='slug',
        ),
        migrations.AlterField(
            model_name='projects',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
